### ISSUE TITLE
Fucked up response, global variables, music position

### ISSUE THREAD

**Issue by Misiur** [MichaelBelgium/Youtube#2]
For some reason the service doesn't return text API response, only full site for some youtube links but not for others, say [this for example](http://www.youtubeinmp3.com/fetch/?format=text&video=https://www.youtube.com/watch?v=ZNbVtrgcsI8) (I suspect cloudflare might have to do with this). I couldn't find any other yt -> mp3 service offering API, so I guess we're stuck with this one. I sugest checking if html is returned by accident and returning error instead of trying to parse response.

Another thing: Even tho we are playing music on per player basis, there are only 3 global variables, so every other player will overwrite previous player's music metadata. 

https://wiki.sa-mp.com/wiki/PlayAudioStreamForPlayer - Also, I suggest allowing other parameters for music position

**Comment by MichaelBelgium** [comment]
I am indeed aware of the redirection to a normal html page. But I assume that happens when the conversion takes longer than normal, and your example is almost 1 hour long. But then again it happens sometimes on normal video's also...

**Comment by Misiur** [comment]
Yea, it happens at random, almost always for <30s movies. http://www.youtubeinmp3.com/fetch/?format=text&video=https://www.youtube.com/watch?v=OgnR5EzsoXg I contacted their support email, maybe they'll consider fixing this.

**Comment by Misiur** [comment]
Ref https://github.com/MichaelBelgium/Youtube/pull/1/commits/44f41f05c362c5529133bbab1926d3fa0446e5d9 
I added custom error message if the first 5 chars of response are "<meta"

**Comment by MichaelBelgium** [comment]
Thanks for sending that e-mail, didn't even think about that. 

Will also do your suggestion in case any one uses those position parameters and fixing the global variables

**Comment by MichaelBelgium** [comment]
Updated now https://github.com/MichaelBelgium/Youtube/commit/c22813e0f6fc295be300f1ee31f407cd0d40da6a

I can not test this currently so I don't know if this works. About the positions, will do that later (unless you are faster)
