### ISSUE TITLE
Retesting this script gives me 2 issues and there's no logic behind it. 

### ISSUE THREAD

**Issue by MichaelBelgium** [MichaelBelgium/Youtube#3]
* The boolean ```Youtube[playerid][Usepos] ``` returns value 116 after doing HTTP request out of nowhere - sometimes just before it also. Generaly it happens after assigning the  ``` usepos``` to the global variable in the ```PlayYoutubeVideoForPlayer```. So it ALWAYS uses usepos in the ```PlayAudioStreamForPlayer``` function
* The video title ( ``` Youtube[playerid][Title]``` ) returns the right value while ```GetVideoTitle()``` returns only the first letter.

```PAWN

//...

stock PlayYoutubeVideoForPlayer(playerid, url[], start = 0, Float:distance = 50.0, bool:usepos = false)
{
	printf("usepos: %d", usepos);

	if(strfind(url,"&") != -1) strmid(url,url,0,strfind(url,"&"),128);
	Youtube[playerid][Distance] = distance;
	Youtube[playerid][Usepos] = usepos;
	format(Youtube[playerid][Link],256,"%s",url);

	printf("usepos: %d", Youtube[playerid][Usepos]);
	format(url,128,"youtubeinmp3.com/fetch/?format=text&video=%s&start=%i",Youtube[playerid][Link],start);
	HTTP(playerid, HTTP_GET, url, "", "OnYoutubeResponse");
}

//...

public OnYoutubeResponse(playerid, response_code, data[])
{
	new error[128];

	if(response_code == 200)
	{
		if (!strcmp(data, "<meta", true, 5))
		{
			//...
		}
		else
		{
			new content[3][256],stream[256],string[256],Float:pos[3];
			new hours,minutes,seconds,tmp_seconds[8];

			explode(content,data,"<br/>");

			strmid(Youtube[playerid][Title], content[0], 7, strlen(content[0]), 256);
			strmid(tmp_seconds,content[1],8,strlen(content[1]));
			strmid(stream,content[2],6,strlen(content[2]));

			printf("Title: %s | Title get: %s | usepos: %d", Youtube[playerid][Title], GetVideoTitle(playerid), Youtube[playerid][Usepos]);

			Youtube[playerid][Duration] = strval(tmp_seconds);
			if(Youtube[playerid][Usepos] == true) GetPlayerPos(playerid, pos[0], pos[1], pos[2]);

			formatSeconds(Youtube[playerid][Duration],hours,minutes,seconds);
			
	  		//...
		}
	}
	else
	{
		//...
	}
}
```

Output with command ```/test https://www.youtube.com/watch?v=1-xGerv5FOk```:

```
usepos: 0
usepos: 116
Title: Alan Walker - Alone  | Title get: A | usepos: 116
```

I hope I'm the only one with this. I have no clue why it happens on my pc.
If there are others having this issue please confirm.

**Comment by yugecin** [comment]
```
enum e_yt
{
	bool:Playing,
	Duration,
	Title[256],
	Link,
	Float: Distance,
	bool: Usepos
};
```
`Link` should be an array because you insert a string of 256 chars into it:
`format(Youtube[playerid][Link],256,"%s",url);`
because it isn't, it is overwriting other data (distance, usepos and other memory that's next to it)

**Comment by yugecin** [comment]
Returning strings always cause pesky bugs, I think it doesn't handle it well because you save it in an enum. It works fine if you first copy it into a new string first:
```
stock GetVideoTitle(ofplayerid) {
    new str[256];
    strins(str, Youtube[ofplayerid][Title], 0);
    return str;
}
```

**Comment by MichaelBelgium** [comment]
Well okay, in other words I was blind :')
